// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDF6QPtKwOru-BXg2bjOXgKpIekvtlw4Bk',
    appId: '1:648688686445:web:9f5e289c525e5b2bb8f664',
    messagingSenderId: '648688686445',
    projectId: 'ecommerce-getx-eb243',
    authDomain: 'ecommerce-getx-eb243.firebaseapp.com',
    storageBucket: 'ecommerce-getx-eb243.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyChtxHEJ4mYFUor6exWhlnXLc1H9lSm83A',
    appId: '1:648688686445:android:26e692c96f73a03eb8f664',
    messagingSenderId: '648688686445',
    projectId: 'ecommerce-getx-eb243',
    storageBucket: 'ecommerce-getx-eb243.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAoXiM8Jd9QSngJf6GXVVzgwlxMfYIG42k',
    appId: '1:648688686445:ios:d40bedc8cb38b2e7b8f664',
    messagingSenderId: '648688686445',
    projectId: 'ecommerce-getx-eb243',
    storageBucket: 'ecommerce-getx-eb243.appspot.com',
    iosBundleId: 'com.example.ecommerceGetxPhpMysql',
  );
}
